package util;

import com.justinquinnb.markon.builtin.converters.BasicApplier;
import com.justinquinnb.markon.builtin.converters.BasicParser;
import com.justinquinnb.markon.model.MarkupLanguage;
import com.justinquinnb.markon.model.conversion.abstractlang.AbstractContent;
import com.justinquinnb.markon.model.conversion.abstractlang.AbstractContentTree;
import com.justinquinnb.markon.model.conversion.application.MarkupApplier;
import com.justinquinnb.markon.model.conversion.parsing.MarkupParser;

/**
 * Comparison utilities for test cases
 */
public class ResultComparer {
    private MarkupParser parser;
    private MarkupApplier applier;
    private MarkupLanguage lang;

    /**
     * Instantiates a {@code ResultComparer} for the given {@link MarkupLanguage} {@code lang} using the
     * provided {@code parser} and {@code applier}.
     *
     * @param parser the parser to use when performing comparisons
     * @param applier the applier to use when performing comparisons
     * @param lang the {@link MarkupLanguage} the text being compared uses
     */
    public ResultComparer(BasicParser parser, BasicApplier applier, MarkupLanguage lang) {
        this.parser = parser;
        this.applier = applier;
        this.lang = lang;
    }

    /**
     * Determines whether {@code this} {@code ResultComparer}'s {@link MarkupParser} correctly
     * digests the provided {@code rawText} to produce the {@code expectedDigestion}.
     *
     * @param rawText the raw text to parse into the {@link AbstractContent} whose digested
     *                string is checked against the {@code expectedDigestion}
     * @param expectedDigestion the digested text the parser should have derived from digesting the
     *                          {@code rawText}
     *
     * @throws AssertionError if the digested text of the {@link AbstractContent} generated by
     * applying {@code this} {@code ResultComparer}'s {@link MarkupParser} to the {@code rawText}
     * matches the {@code expectedDigestion}
     */
    public void digestionIsValid(String rawText, String expectedDigestion) throws AssertionError {
        AbstractContentTree contentTree = parser.parse(rawText, lang);
        String digestedText = contentTree.getData().getDigestedString();
        String failureMessage = String.format("'%s' was digested into '%s', not '%s'", rawText,
            digestedText, expectedDigestion);
        assert digestedText.equals(expectedDigestion): failureMessage;
    }
}
