package com.justinquinnb.markon.model.conversion.parsing;

import com.justinquinnb.markon.model.conversion.abstractlang.AbstractContent;
import java.util.List;

/**
 * A parser method's response. All {@link #parsedContent} should be positioned with respect to the
 * displacement generated by its sibling {@link ParsedContent} pieces in the list.<br><br>
 *
 * For example, if one parsing method operation reduces the length of a string
 * that precedes another piece of {@code ParsedContent} in the returned {@link #parsedContent} list,
 * then the following piece should have its position adjusted accordingly.<br>
 * {@code ~TEXT1~ TEXT2 |TEXT3|}
 * <ol>
 *     <li>Matches the entire: {@code ~TEXT1~ TEXT2 |TEXT3|}</li>
 *     <li>Digests {@code [0,6]} into ~ formatting: {@code TEXT1 [0,4]}</li>
 *     <li>Digests {@code [8,14]} into plaintext formatting: {@code TEXT2 [8,12]}</li>
 *     <li>Digests {@code [16,22]} into {@code |} formatting: {@code TEXT3 [16,20]}</li>
 *     <li>Adjusts the position of the plaintext piece to {@code [6,10]}</li>
 *     <li>Adjusts the position of the {@code |} formatting piece to {@code [12,16]}</li>
 *     <li>Returns: [{@code ~ style at [0,4]}, {@code plaintext TEXT2 at [6,10]}, {@code | style TEXT3 at [12,16]}]</li>
 * </ol>
 */
public class ParserResponse {
    private final List<ParsedContent> parsedContent;

    public ParserResponse(ParsedContent... parsedContent) {
        this.parsedContent = List.of(parsedContent);
    }

    public ParserResponse(List<ParsedContent> parsedContent) {
        this.parsedContent = parsedContent;
    }

    public List<ParsedContent> getContent() {
        return parsedContent;
    }

    public static ParserResponse of(ParsedContent... parsedContent) {
        return new ParserResponse(List.of(parsedContent));
    }

    public static ParserResponse of(AbstractContent content) {
        return new ParserResponse(new ParsedContent(content));
    }

    public static ParserResponse of(AbstractContent content, boolean ignoreEmbedded) {
        return new ParserResponse(new ParsedContent(content, ignoreEmbedded));
    }
}
